[2022-08-29T17:38:38.308-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v05.get_name manual__2022-08-29T21:38:35.139128+00:00 [queued]>
[2022-08-29T17:38:38.322-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_python_operator_v05.get_name manual__2022-08-29T21:38:35.139128+00:00 [queued]>
[2022-08-29T17:38:38.323-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-29T17:38:38.323-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-08-29T17:38:38.323-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-29T17:38:38.379-0400] {taskinstance.py:1389} INFO - Executing <Task(PythonOperator): get_name> on 2022-08-29 21:38:35.139128+00:00
[2022-08-29T17:38:38.383-0400] {standard_task_runner.py:52} INFO - Started process 6920 to run task
[2022-08-29T17:38:38.388-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_python_operator_v05', 'get_name', 'manual__2022-08-29T21:38:35.139128+00:00', '--job-id', '11', '--raw', '--subdir', '/home/augenz/PycharmProjects/airflow/dags/dag_with_python_operator_v05.py', '--cfg-path', '/run/user/1000/app/com.jetbrains.PyCharm-Community/tmpt1ukhmeu', '--error-file', '/run/user/1000/app/com.jetbrains.PyCharm-Community/tmpz6hk6i6o']
[2022-08-29T17:38:38.389-0400] {standard_task_runner.py:80} INFO - Job 11: Subtask get_name
[2022-08-29T17:38:38.566-0400] {task_command.py:371} INFO - Running <TaskInstance: dag_with_python_operator_v05.get_name manual__2022-08-29T21:38:35.139128+00:00 [running]> on host pop-os.localdomain
[2022-08-29T17:38:38.758-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=dag_with_python_operator_v05
AIRFLOW_CTX_TASK_ID=get_name
AIRFLOW_CTX_EXECUTION_DATE=2022-08-29T21:38:35.139128+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-29T21:38:35.139128+00:00
[2022-08-29T17:38:38.879-0400] {python.py:173} INFO - Done. Returned value was: None
[2022-08-29T17:38:38.909-0400] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=dag_with_python_operator_v05, task_id=get_name, execution_date=20220829T213835, start_date=20220829T213838, end_date=20220829T213838
[2022-08-29T17:38:38.966-0400] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-29T17:38:39.095-0400] {local_task_job.py:279} INFO - 1 downstream tasks scheduled from follow-on schedule check
