[2022-08-29T22:01:36.170-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-08-30T02:01:25.664737+00:00 [queued]>
[2022-08-29T22:01:36.197-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-08-30T02:01:25.664737+00:00 [queued]>
[2022-08-29T22:01:36.198-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-29T22:01:36.198-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-08-29T22:01:36.199-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-29T22:01:36.269-0400] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-08-30 02:01:25.664737+00:00
[2022-08-29T22:01:36.281-0400] {standard_task_runner.py:52} INFO - Started process 16690 to run task
[2022-08-29T22:01:36.287-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2022-08-30T02:01:25.664737+00:00', '--job-id', '51', '--raw', '--subdir', '/home/augenz/PycharmProjects/airflow/dags/dag_with_postgres_operator_v01.py', '--cfg-path', '/run/user/1000/app/com.jetbrains.PyCharm-Community/tmpurau8ix9', '--error-file', '/run/user/1000/app/com.jetbrains.PyCharm-Community/tmp2ow9rr8z']
[2022-08-29T22:01:36.289-0400] {standard_task_runner.py:80} INFO - Job 51: Subtask create_postgres_table
[2022-08-29T22:01:36.537-0400] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-08-30T02:01:25.664737+00:00 [running]> on host pop-os.localdomain
[2022-08-29T22:01:36.761-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-30T02:01:25.664737+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-30T02:01:25.664737+00:00
[2022-08-29T22:01:36.787-0400] {base.py:68} INFO - Using connection ID 'database-server_postgres' for task execution.
[2022-08-29T22:01:36.803-0400] {sql.py:315} INFO - Running statement: CREATE TABLE IF NOT EXISTS dag_runs (
            df date,
            dag_id character varying,
            primary key (dt, dag_id)
            ), parameters: None
[2022-08-29T22:01:36.805-0400] {taskinstance.py:1902} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/augenz/PycharmProjects/airflow/.env_airflow/lib/python3.9/site-packages/airflow/providers/postgres/operators/postgres.py", line 92, in execute
    self.hook.run(self.sql, self.autocommit, parameters=self.parameters)
  File "/home/augenz/PycharmProjects/airflow/.env_airflow/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 295, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/augenz/PycharmProjects/airflow/.env_airflow/lib/python3.9/site-packages/airflow/providers/common/sql/hooks/sql.py", line 320, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.UndefinedColumn: column "dt" named in key does not exist
LINE 4:             primary key (dt, dag_id)
                    ^

[2022-08-29T22:01:36.854-0400] {taskinstance.py:1407} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20220830T020125, start_date=20220830T020136, end_date=20220830T020136
[2022-08-29T22:01:36.902-0400] {standard_task_runner.py:92} ERROR - Failed to execute job 51 for task create_postgres_table (column "dt" named in key does not exist
LINE 4:             primary key (dt, dag_id)
                    ^
; 16690)
[2022-08-29T22:01:36.947-0400] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-29T22:01:37.060-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-29T22:05:02.097-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-08-30T02:01:25.664737+00:00 [queued]>
[2022-08-29T22:05:02.129-0400] {taskinstance.py:1171} INFO - Dependencies all met for <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-08-30T02:01:25.664737+00:00 [queued]>
[2022-08-29T22:05:02.130-0400] {taskinstance.py:1368} INFO - 
--------------------------------------------------------------------------------
[2022-08-29T22:05:02.130-0400] {taskinstance.py:1369} INFO - Starting attempt 1 of 6
[2022-08-29T22:05:02.130-0400] {taskinstance.py:1370} INFO - 
--------------------------------------------------------------------------------
[2022-08-29T22:05:02.181-0400] {taskinstance.py:1389} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2022-08-30 02:01:25.664737+00:00
[2022-08-29T22:05:02.186-0400] {standard_task_runner.py:52} INFO - Started process 16840 to run task
[2022-08-29T22:05:02.191-0400] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_postgres_operator_v01', 'create_postgres_table', 'manual__2022-08-30T02:01:25.664737+00:00', '--job-id', '52', '--raw', '--subdir', '/home/augenz/PycharmProjects/airflow/dags/dag_with_postgres_operator_v02.py', '--cfg-path', '/run/user/1000/app/com.jetbrains.PyCharm-Community/tmpwzrzq6cy', '--error-file', '/run/user/1000/app/com.jetbrains.PyCharm-Community/tmp29xjjy0j']
[2022-08-29T22:05:02.193-0400] {standard_task_runner.py:80} INFO - Job 52: Subtask create_postgres_table
[2022-08-29T22:05:02.394-0400] {task_command.py:371} INFO - Running <TaskInstance: dag_with_postgres_operator_v01.create_postgres_table manual__2022-08-30T02:01:25.664737+00:00 [running]> on host pop-os.localdomain
[2022-08-29T22:05:02.626-0400] {taskinstance.py:1581} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=admin
AIRFLOW_CTX_DAG_ID=dag_with_postgres_operator_v01
AIRFLOW_CTX_TASK_ID=create_postgres_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-30T02:01:25.664737+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-30T02:01:25.664737+00:00
[2022-08-29T22:05:02.657-0400] {base.py:68} INFO - Using connection ID 'database-server_postgres' for task execution.
[2022-08-29T22:05:02.673-0400] {sql.py:315} INFO - Running statement: CREATE TABLE IF NOT EXISTS dag_runs (
            dt date,
            dag_id character varying,
            primary key (dt, dag_id)
            ), parameters: None
[2022-08-29T22:05:02.812-0400] {taskinstance.py:1407} INFO - Marking task as SUCCESS. dag_id=dag_with_postgres_operator_v01, task_id=create_postgres_table, execution_date=20220830T020125, start_date=20220830T020502, end_date=20220830T020502
[2022-08-29T22:05:02.900-0400] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-29T22:05:03.039-0400] {local_task_job.py:279} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-08-29T22:05:03.103-0400] {dagrun.py:567} INFO - Marking run <DagRun dag_with_postgres_operator_v01 @ 2022-08-30 02:01:25.664737+00:00: manual__2022-08-30T02:01:25.664737+00:00, state:running, queued_at: 2022-08-30 02:01:25.759651+00:00. externally triggered: True> successful
[2022-08-29T22:05:03.104-0400] {dagrun.py:612} INFO - DagRun Finished: dag_id=dag_with_postgres_operator_v01, execution_date=2022-08-30 02:01:25.664737+00:00, run_id=manual__2022-08-30T02:01:25.664737+00:00, run_start_date=2022-08-30 02:01:26.659014+00:00, run_end_date=2022-08-30 02:05:03.104708+00:00, run_duration=216.445694, state=success, external_trigger=True, run_type=manual, data_interval_start=2022-08-29 00:00:00+00:00, data_interval_end=2022-08-30 00:00:00+00:00, dag_hash=220c29d1338056f01514245527a7c9a4
